
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async increaseCounter() : Promise<number> {
    return await TAURI_INVOKE("increase_counter");
},
async getRootPath() : Promise<string> {
    return await TAURI_INVOKE("get_root_path");
},
async setRootPath(path: string) : Promise<string> {
    return await TAURI_INVOKE("set_root_path", { path });
},
async addProject(remoteUrl: string, projectName: string) : Promise<RepositoryInfo[]> {
    return await TAURI_INVOKE("add_project", { remoteUrl, projectName });
},
async cloneRepository(remoteUrl: string, projectName: string) : Promise<Result<RepositoryInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_repository", { remoteUrl, projectName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateRepoName(name: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_repo_name", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepositories() : Promise<RepositoryInfo[]> {
    return await TAURI_INVOKE("get_repositories");
},
async getFilteredTags(repoPath: string) : Promise<Result<TagInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_filtered_tags", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshRepository(repoId: number) : Promise<Result<RepositoryInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_repository", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVersion(repoId: number, tag: string) : Promise<Result<RepositoryInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_version", { repoId, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRepository(repoId: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_repository", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveState() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadState() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appInitializeEvent: AppInitializeEvent,
cloneCompleteEvent: CloneCompleteEvent,
cloneProgressEvent: CloneProgressEvent
}>({
appInitializeEvent: "app-initialize-event",
cloneCompleteEvent: "clone-complete-event",
cloneProgressEvent: "clone-progress-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppInitializeEvent = { repository_datas: RepositoryInfo[]; auth_token: string; root_path: string; app_version: string }
export type CloneCompleteEvent = { repo_name: string; success: boolean; error_message: string | null }
export type CloneProgressEvent = { repo_name: string; progress: number; message: string; receivedBytes: number | null; totalObjects: number | null; receivedObjects: number | null; speed: string | null }
export type RepositoryInfo = { id: number; name: string; remote_url: string; branch: string; path: string; gameVersion: string; gameVersions: string[]; server: string; serverOptions: string[]; hasWarning: boolean; lastSyncTime: string | null }
export type TagInfo = { originalTag: string; displayName: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
